Documentation dashboard page
landinfotech/mycivitas pull request #31
Opened 2024-02-09 05:49 UTC by ketankartoza

This PR is for issue #24

2024-02-12 08:55 UTC, Jeremy-Prior requested changes

2024-02-12 08:55 UTC, Jeremy-Prior commented on docs/src/user/manual/dashboard.md
> +Welcome to the `Dashboard` page, a centralized hub for a quick overview of linked communities. Follow this user manual to navigate and make the most out of the dashboard experience.
```suggestion
Welcome to the `Dashboard` page, a centralised hub for a quick overview of linked communities. Follow this user manual to navigate and make the most out of the dashboard experience.
```

2024-02-12 08:55 UTC, Jeremy-Prior commented on docs/src/user/manual/dashboard.md
> +            2. **Available Options on Chart:** Explore various options on the chart for enhanced visualization:
```suggestion
            2. **Available Options on Chart:** Explore various options on the chart for enhanced visualisation:
```

2024-02-12 08:55 UTC, Jeremy-Prior commented on docs/src/user/manual/dashboard.md
> +            - **Lasso Select Image:** Utilize the lasso select image option for precise graph selection.
```suggestion
            - **Lasso Select Image:** Utilise the lasso select image option for precise graph selection.
```

2024-02-12 08:55 UTC, Jeremy-Prior commented on docs/src/user/manual/dashboard.md
> +            - **Auto Scale Image:** Automatically scale the graph for optimal visualization.
```suggestion
            - **Auto Scale Image:** Automatically scale the graph for optimal visualisation.
```

2024-02-12 08:55 UTC, Jeremy-Prior commented on docs/src/user/manual/dashboard.md
> +        3. **Annual Average Infrastructure Demand:** This graph uses lifespan projections and renewal costs for a long-term outlook of infrastructure. This projection is theoretical and is not a real
```suggestion
        3. **Annual Average Infrastructure Demand:** This graph uses lifespan projections and renewal costs for a long-term outlook of infrastructure. This projection is theoretical and is not a realistic indication of spending timelines. A valuable output of this projection is an annualised infrastructure demand, indicated as a dotted line on the graph. This annualised value is obtained by dividing the renewal cost by the lifespan for each asset in the database and then summing the total. As lifespan and renewal cost data are updated, the annual infrastructure demand will update. The annual infrastructure demand could be lowered by committing to operations and maintenance programs to extend lifespans, deciding to rehabilitate versus replace, and more. The values shown in the graph are based on current $ values and the actual value of this average annual investment will increase over time with inflation.
```

2024-02-12 08:55 UTC, Jeremy-Prior commented on docs/src/user/manual/dashboard.md
> +        4. **Risk By System:** A risk value is obtained by combining Probability of Failure (PoF) and Consequence of Failure (CoF) values as per the following matrix. It is common asset management pr
```suggestion
        4. **Risk By System:** A risk value is obtained by combining Probability of Failure (PoF) and Consequence of Failure (CoF) values as per the following matrix. It is common asset management practice to shift the matrix in favour of the consequence of failure.
```

2024-02-12 08:55 UTC, Jeremy-Prior commented on docs/src/user/manual/dashboard.md
> +        6. **Remaining Years by Renewal Cost by Risk:** This section offers a detailed analysis of the remaining operational years of a system to its renewal cost and associated risk factors. Underst
```suggestion
        6. **Remaining Years by Renewal Cost by Risk:** This section offers a detailed analysis of the remaining operational years of a system to its renewal cost and associated risk factors. Understand how the remaining lifespan of different systems correlates with their renewal costs and associated risks. Use this valuable information to prioritise and strategise system maintenance, considering both financial and risk considerations. Enhance decision-making processes by leveraging insights into the intersection of system longevity, renewal costs, and associated risks.
```

2024-02-13 07:01 UTC, Jeremy-Prior approved these changes
LGTM

2024-02-13 07:01 UTC, Jeremy-Prior commented
@ketankartoza please resolve the conflicts

2024-02-13 07:10 UTC, ketankartoza commented
> @ketankartoza please resolve the conflicts

@Jeremy-Prior Done!

2024-02-13 07:22 UTC, Jeremy-Prior approved these changes
LGTM

2024-02-13 07:22 UTC, merged