Developer documentation
landinfotech/mycivitas pull request #94
Opened 2024-03-14 09:39 UTC by ketankartoza

This PR is for the issue #92

2024-03-15 06:59 UTC, voogt approved these changes

2024-03-22 07:58 UTC, Jeremy-Prior requested changes

2024-03-22 07:58 UTC, Jeremy-Prior commented on docs/src/developer/guide/cloning.md
> +Git Code check out [PROJECT_URL](https://github.com/landinfotech/mycivitas) <!-- Change this per project -->
```suggestion
Git Code check out https://github.com/landinfotech/mycivitas
```

2024-03-22 07:58 UTC, Jeremy-Prior commented on docs/src/developer/guide/prerequisites.md
> +# Project Prerequisites
Need the header section before this.

2024-03-25 06:44 UTC, Jeremy-Prior approved these changes
LGTM

2024-03-25 06:44 UTC, merged